const eAPS = [
  // ── Brasil (50 aeroportos) ─────────────────────
  {code:'GRU',name:'São Paulo-Guarulhos',city:'São Paulo',country:'Brasil',flag:'🇧🇷',x:40,y:72,type:'main',alt:['sp','sampa','guarulhos'],lat:-23.43,lng:-46.47},
  {code:'CGH',name:'São Paulo-Congonhas',city:'São Paulo',country:'Brasil',flag:'🇧🇷',x:40,y:72,type:'budget',alt:['sp','congonhas'],lat:-23.63,lng:-46.66},
  {code:'VCP',name:'Campinas-Viracopos',city:'Campinas',country:'Brasil',flag:'🇧🇷',x:40,y:72,type:'budget',alt:['campinas','viracopos'],lat:-23.01,lng:-47.13},
  {code:'GIG',name:'Rio-Galeão',city:'Rio de Janeiro',country:'Brasil',flag:'🇧🇷',x:41,y:71,type:'main',alt:['rj','rio','galeao'],lat:-22.81,lng:-43.25},
  {code:'SDU',name:'Rio-Santos Dumont',city:'Rio de Janeiro',country:'Brasil',flag:'🇧🇷',x:41,y:71,type:'budget',alt:['rj','rio','santos dumont'],lat:-22.91,lng:-43.17},
  {code:'BSB',name:'Brasília-Presidente JK',city:'Brasília',country:'Brasil',flag:'🇧🇷',x:37,y:68,type:'main',alt:['df','bsb','distrito federal'],lat:-15.86,lng:-47.92},
  {code:'CNF',name:'BH-Confins Tancredo Neves',city:'Belo Horizonte',country:'Brasil',flag:'🇧🇷',x:38,y:70,type:'main',alt:['bh','bhz','confins','minas gerais'],lat:-19.63,lng:-43.97},
  {code:'PLU',name:'BH-Pampulha Carlos Drummond',city:'Belo Horizonte',country:'Brasil',flag:'🇧🇷',x:38,y:70,type:'budget',alt:['bh','bhz','pampulha'],lat:-19.85,lng:-43.9},
  {code:'SSA',name:'Salvador-Dep. Luís Eduardo',city:'Salvador',country:'Brasil',flag:'🇧🇷',x:40,y:63,type:'main',alt:['ssa','bahia'],lat:-12.91,lng:-38.33},
  {code:'REC',name:'Recife-Guararapes',city:'Recife',country:'Brasil',flag:'🇧🇷',x:42,y:59,type:'main',alt:['rec','pernambuco'],lat:-8.13,lng:-34.92},
  {code:'FOR',name:'Fortaleza-Pinto Martins',city:'Fortaleza',country:'Brasil',flag:'🇧🇷',x:40,y:56,type:'main',alt:['for','ceara'],lat:-3.78,lng:-38.53},
  {code:'BEL',name:'Belém-Val-de-Cans',city:'Belém',country:'Brasil',flag:'🇧🇷',x:36,y:58,type:'main',alt:['bel','para','amazonia'],lat:-1.38,lng:-48.48},
  {code:'MAO',name:'Manaus-Eduardo Gomes',city:'Manaus',country:'Brasil',flag:'🇧🇷',x:31,y:60,type:'main',alt:['mao','amazonas'],lat:-3.04,lng:-60.05},
  {code:'CWB',name:'Curitiba-Afonso Pena',city:'Curitiba',country:'Brasil',flag:'🇧🇷',x:39,y:74,type:'main',alt:['cwb','parana'],lat:-25.53,lng:-49.18},
  {code:'FLN',name:'Florianópolis-Hercílio Luz',city:'Florianópolis',country:'Brasil',flag:'🇧🇷',x:39,y:75,type:'main',alt:['fln','floripa','santa catarina'],lat:-27.67,lng:-48.55},
  {code:'POA',name:'Porto Alegre-Salgado Filho',city:'Porto Alegre',country:'Brasil',flag:'🇧🇷',x:38,y:78,type:'main',alt:['poa','rs','rio grande do sul'],lat:-29.99,lng:-51.17},
  {code:'NAT',name:'Natal-São Gonçalo do Amarante',city:'Natal',country:'Brasil',flag:'🇧🇷',x:42,y:57,type:'main',alt:['nat','rn','rio grande do norte'],lat:-5.91,lng:-35.25},
  {code:'MCZ',name:'Maceió-Zumbi dos Palmares',city:'Maceió',country:'Brasil',flag:'🇧🇷',x:42,y:61,type:'main',alt:['mcz','alagoas'],lat:-9.51,lng:-35.79},
  {code:'AJU',name:'Aracaju-Santa Maria',city:'Aracaju',country:'Brasil',flag:'🇧🇷',x:41,y:62,type:'main',alt:['aju','sergipe'],lat:-10.98,lng:-37.07},
  {code:'JPA',name:'João Pessoa-Pres. Castro Pinto',city:'João Pessoa',country:'Brasil',flag:'🇧🇷',x:42,y:58,type:'main',alt:['jpa','paraiba'],lat:-7.15,lng:-34.95},
  {code:'THE',name:'Teresina-Senador Petrônio Portela',city:'Teresina',country:'Brasil',flag:'🇧🇷',x:39,y:58,type:'main',alt:['the','piaui'],lat:-5.06,lng:-42.82},
  {code:'SLZ',name:'São Luís-Marechal Cunha Machado',city:'São Luís',country:'Brasil',flag:'🇧🇷',x:38,y:57,type:'main',alt:['slz','maranhao'],lat:-2.59,lng:-44.24},
  {code:'VIX',name:'Vitória-Eurico Salles',city:'Vitória',country:'Brasil',flag:'🇧🇷',x:40,y:70,type:'main',alt:['vix','espirito santo'],lat:-20.26,lng:-40.29},
  {code:'GYN',name:'Goiânia-Santa Genoveva',city:'Goiânia',country:'Brasil',flag:'🇧🇷',x:37,y:67,type:'main',alt:['gyn','goias'],lat:-16.63,lng:-49.22},
  {code:'CGB',name:'Cuiabá-Marechal Rondon',city:'Cuiabá',country:'Brasil',flag:'🇧🇷',x:34,y:65,type:'main',alt:['cgb','mato grosso','pantanal'],lat:-15.65,lng:-56.12},
  {code:'CGR',name:'Campo Grande-Antonio J. Palhano',city:'Campo Grande',country:'Brasil',flag:'🇧🇷',x:35,y:68,type:'main',alt:['cgr','ms','mato grosso do sul'],lat:-20.47,lng:-54.67},
  {code:'PMW',name:'Palmas-Brigadeiro Lysias Rodrigues',city:'Palmas',country:'Brasil',flag:'🇧🇷',x:36,y:62,type:'main',alt:['pmw','tocantins'],lat:-10.29,lng:-48.36},
  {code:'RBR',name:'Rio Branco-Plácido de Castro',city:'Rio Branco',country:'Brasil',flag:'🇧🇷',x:27,y:63,type:'main',alt:['rbr','acre'],lat:-9.86,lng:-67.89},
  {code:'PVH',name:'Porto Velho-Governador Jorge Teixeira',city:'Porto Velho',country:'Brasil',flag:'🇧🇷',x:29,y:62,type:'main',alt:['pvh','rondonia'],lat:-8.71,lng:-63.9},
  {code:'BVB',name:'Boa Vista-Atlântico',city:'Boa Vista',country:'Brasil',flag:'🇧🇷',x:31,y:55,type:'main',alt:['bvb','roraima'],lat:2.84,lng:-60.69},
  {code:'MCP',name:'Macapá-Alberto Alcolumbre',city:'Macapá',country:'Brasil',flag:'🇧🇷',x:35,y:56,type:'main',alt:['mcp','amapa'],lat:0.05,lng:-51.07},
  {code:'IMP',name:'Imperatriz-Prefeito Renato Moreira',city:'Imperatriz',country:'Brasil',flag:'🇧🇷',x:37,y:60,type:'sec',alt:['imp','maranhao'],lat:-5.53,lng:-47.46},
  {code:'IOS',name:'Ilhéus-Jorge Amado',city:'Ilhéus',country:'Brasil',flag:'🇧🇷',x:40,y:65,type:'sec',alt:['ios','bahia','costa do cacau'],lat:-14.82,lng:-39.03},
  {code:'LEC',name:'Lençóis-Horácio de Matos',city:'Lençóis',country:'Brasil',flag:'🇧🇷',x:39,y:63,type:'sec',alt:['lec','chapada diamantina','bahia']},
  {code:'BPS',name:'Porto Seguro',city:'Porto Seguro',country:'Brasil',flag:'🇧🇷',x:40,y:65,type:'sec',alt:['bps','bahia','descobrimento'],lat:-16.44,lng:-39.08},
  {code:'IGU',name:'Foz do Iguaçu-Cat. das Cataratas',city:'Foz do Iguaçu',country:'Brasil',flag:'🇧🇷',x:36,y:74,type:'main',alt:['igu','iguassu','iguazu','cataratas','foz']},
  {code:'CFB',name:'Cabo Frio',city:'Cabo Frio',country:'Brasil',flag:'🇧🇷',x:41,y:72,type:'sec',alt:['cfb','rj','buzios']},
  {code:'BZC',name:'Buzios-Umberto Modiano',city:'Búzios',country:'Brasil',flag:'🇧🇷',x:41,y:72,type:'sec',alt:['bzc','buzios','rj']},
  {code:'UDI',name:'Uberlândia-Ten. Cel. Aviador César Bombonato',city:'Uberlândia',country:'Brasil',flag:'🇧🇷',x:37,y:68,type:'sec',alt:['udi','mg','minas'],lat:-18.88,lng:-48.23},
  {code:'JDO',name:'Juazeiro do Norte-Orlando Bezerra',city:'Juazeiro do Norte',country:'Brasil',flag:'🇧🇷',x:40,y:59,type:'sec',alt:['jdo','ce','ceara','crato'],lat:-7.22,lng:-39.27},
  {code:'OPS',name:'Sinop',city:'Sinop',country:'Brasil',flag:'🇧🇷',x:33,y:63,type:'sec',alt:['ops','mato grosso']},
  {code:'CPV',name:'Campina Grande-Presidente João Suassuna',city:'Campina Grande',country:'Brasil',flag:'🇧🇷',x:42,y:58,type:'sec',alt:['cpv','pb','paraiba'],lat:-7.6,lng:-39.17},
  // ── América do Sul ──────────────────────────────
  {code:'EZE',name:'Buenos Aires-Ezeiza',city:'Buenos Aires',country:'Argentina',flag:'🇦🇷',x:36,y:80,type:'main',alt:['ba','baires','argentina'],lat:-34.82,lng:-58.53},
  {code:'AEP',name:'Buenos Aires-Aeroparque',city:'Buenos Aires',country:'Argentina',flag:'🇦🇷',x:36,y:80,type:'budget',alt:['ba','aeroparque'],lat:-34.56,lng:-58.42},
  {code:'COR',name:'Córdoba-Ingeniero Taravella',city:'Córdoba',country:'Argentina',flag:'🇦🇷',x:33,y:79,type:'main',alt:['cor','cordoba argentina'],lat:-31.32,lng:-64.21},
  {code:'SCL',name:'Santiago-Arturo Merino Benítez',city:'Santiago',country:'Chile',flag:'🇨🇱',x:31,y:78,type:'main',alt:['scl','chile'],lat:-33.39,lng:-70.79},
  {code:'LIM',name:'Lima-Jorge Chávez',city:'Lima',country:'Peru',flag:'🇵🇪',x:27,y:64,type:'main',alt:['lim','peru'],lat:-12.02,lng:-77.11},
  {code:'CUZ',name:'Cusco-Alejandro Velasco Astete',city:'Cusco',country:'Peru',flag:'🇵🇪',x:28,y:66,type:'sec',alt:['cuz','cusco','machu picchu'],lat:-13.53,lng:-71.94},
  {code:'BOG',name:'Bogotá-El Dorado',city:'Bogotá',country:'Colômbia',flag:'🇨🇴',x:29,y:57,type:'main',alt:['bog','colombia'],lat:4.7,lng:-74.14},
  {code:'MDE',name:'Medellín-José María Córdova',city:'Medellín',country:'Colômbia',flag:'🇨🇴',x:28,y:55,type:'main',alt:['mde','medellin']},
  {code:'CTG',name:'Cartagena-Rafael Núñez',city:'Cartagena',country:'Colômbia',flag:'🇨🇴',x:27,y:53,type:'main',alt:['ctg','cartagena colombia']},
  {code:'MVD',name:'Montevidéu-Carrasco',city:'Montevidéu',country:'Uruguai',flag:'🇺🇾',x:37,y:78,type:'main',alt:['mvd','uruguay'],lat:-34.84,lng:-56.01},
  {code:'UIO',name:'Quito-Mariscal Sucre',city:'Quito',country:'Equador',flag:'🇪🇨',x:27,y:58,type:'main',alt:['uio','equador'],lat:-0.13,lng:-78.49},
  {code:'GYE',name:'Guayaquil-José Joaquín de Olmedo',city:'Guayaquil',country:'Equador',flag:'🇪🇨',x:26,y:59,type:'main',alt:['gye','galápagos'],lat:-2.16,lng:-79.88},
  {code:'LPB',name:'La Paz-El Alto',city:'La Paz',country:'Bolívia',flag:'🇧🇴',x:30,y:67,type:'main',alt:['lpb','bolivia'],lat:-16.51,lng:-68.19},
  {code:'ASU',name:'Assunção-Silvio Pettirossi',city:'Assunção',country:'Paraguai',flag:'🇵🇾',x:36,y:74,type:'main',alt:['asu','paraguay','assuncao'],lat:-25.24,lng:-57.52},
  {code:'PMC',name:'Puerto Montt-El Tepual',city:'Puerto Montt',country:'Chile',flag:'🇨🇱',x:30,y:84,type:'sec',alt:['pmc','patagonia chile','lago llanquihue'],lat:-38.93,lng:-68.58},
  {code:'FTE',name:'El Calafate-Comandante Armando Tola',city:'El Calafate',country:'Argentina',flag:'🇦🇷',x:31,y:88,type:'sec',alt:['fte','glaciares','patagonia argentina']},
  {code:'USH',name:'Ushuaia-Malvinas Argentinas',city:'Ushuaia',country:'Argentina',flag:'🇦🇷',x:33,y:92,type:'sec',alt:['ush','tierra del fuego','fim do mundo'],lat:-54.84,lng:-68.29},
  // ── Europa ──────────────────────────────────────
  {code:'LIS',name:'Lisboa-Humberto Delgado',city:'Lisboa',country:'Portugal',flag:'🇵🇹',x:45,y:34,type:'main',alt:['lis','portugal','lisbon'],lat:38.78,lng:-9.13},
  {code:'OPO',name:'Porto-Francisco Sá Carneiro',city:'Porto',country:'Portugal',flag:'🇵🇹',x:45,y:32,type:'main',alt:['opo','porto','porto portugal','duoro','douro','portugal norte'],lat:41.24,lng:-8.68},
  {code:'FAO',name:'Faro-Internacional',city:'Faro',country:'Portugal',flag:'🇵🇹',x:45,y:35,type:'main',alt:['fao','algarve','portugal sul']},
  {code:'MAD',name:'Madrid-Adolfo Suárez Barajas',city:'Madrid',country:'Espanha',flag:'🇪🇸',x:48,y:34,type:'main',alt:['mad','espanha','spain'],lat:40.47,lng:-3.56},
  {code:'BCN',name:'Barcelona-El Prat',city:'Barcelona',country:'Espanha',flag:'🇪🇸',x:50,y:33,type:'main',alt:['bcn','barcelona','catalunha'],lat:41.3,lng:2.08},
  {code:'AGP',name:'Málaga-Costa del Sol',city:'Málaga',country:'Espanha',flag:'🇪🇸',x:47,y:35,type:'main',alt:['agp','malaga','andaluzia'],lat:36.67,lng:-4.5},
  {code:'ALC',name:'Alicante-Elche',city:'Alicante',country:'Espanha',flag:'🇪🇸',x:49,y:34,type:'main',alt:['alc','alicante','costa blanca']},
  {code:'PMI',name:'Palma de Maiorca',city:'Palma de Maiorca',country:'Espanha',flag:'🇪🇸',x:50,y:34,type:'main',alt:['pmi','maiorca','mallorca','baleares'],lat:39.55,lng:2.74},
  {code:'CDG',name:'Paris-Charles de Gaulle',city:'Paris',country:'França',flag:'🇫🇷',x:50,y:28,type:'main',alt:['cdg','paris','franca','france'],lat:49.01,lng:2.55},
  {code:'ORY',name:'Paris-Orly',city:'Paris',country:'França',flag:'🇫🇷',x:50,y:28,type:'budget',alt:['ory','paris','orly']},
  {code:'NCE',name:'Nice-Côte d\'Azur',city:'Nice',country:'França',flag:'🇫🇷',x:52,y:31,type:'main',alt:['nce','nice','riviera','monaco'],lat:43.66,lng:7.21},
  {code:'LYS',name:'Lyon-Saint-Exupéry',city:'Lyon',country:'França',flag:'🇫🇷',x:51,y:30,type:'main',alt:['lys','lyon'],lat:45.72,lng:5.09},
  {code:'AMS',name:'Amsterdam-Schiphol',city:'Amsterdã',country:'Holanda',flag:'🇳🇱',x:51,y:25,type:'main',alt:['ams','amsterdam','holanda','netherlands'],lat:52.31,lng:4.77},
  {code:'BER',name:'Berlim-Brandenburg',city:'Berlim',country:'Alemanha',flag:'🇩🇪',x:54,y:24,type:'main',alt:['ber','berlim','berlin','alemanha']},
  {code:'FRA',name:'Frankfurt-Internacional',city:'Frankfurt',country:'Alemanha',flag:'🇩🇪',x:53,y:26,type:'main',alt:['fra','frankfurt','alemanha'],lat:50.03,lng:8.57},
  {code:'MUC',name:'Munique-Franz Josef Strauss',city:'Munique',country:'Alemanha',flag:'🇩🇪',x:54,y:27,type:'main',alt:['muc','munique','munich','baviera'],lat:48.35,lng:11.79},
  {code:'FCO',name:'Roma-Fiumicino Leonardo da Vinci',city:'Roma',country:'Itália',flag:'🇮🇹',x:54,y:33,type:'main',alt:['fco','roma','rome','italia'],lat:41.8,lng:12.25},
  {code:'CIA',name:'Roma-Ciampino',city:'Roma',country:'Itália',flag:'🇮🇹',x:54,y:33,type:'budget',alt:['cia','roma','ciampino']},
  {code:'MXP',name:'Milão-Malpensa',city:'Milão',country:'Itália',flag:'🇮🇹',x:52,y:30,type:'main',alt:['mxp','milao','milan','lombardia'],lat:45.63,lng:8.73},
  {code:'VCE',name:'Veneza-Marco Polo',city:'Veneza',country:'Itália',flag:'🇮🇹',x:53,y:30,type:'main',alt:['vce','veneza','venice','venezia'],lat:45.5,lng:12.35},
  {code:'NAP',name:'Nápoles-Capodichino',city:'Nápoles',country:'Itália',flag:'🇮🇹',x:54,y:34,type:'main',alt:['nap','napoles','naples','amalfi','pompeii']},
  {code:'PMO',name:'Palermo-Falcone Borsellino',city:'Palermo',country:'Itália',flag:'🇮🇹',x:53,y:35,type:'main',alt:['pmo','palermo','sicilia','sicily']},
  {code:'LHR',name:'Londres-Heathrow',city:'Londres',country:'UK',flag:'🇬🇧',x:49,y:25,type:'main',alt:['lhr','londres','london','inglaterra','uk'],lat:51.48,lng:-0.45},
  {code:'LGW',name:'Londres-Gatwick',city:'Londres',country:'UK',flag:'🇬🇧',x:49,y:25,type:'budget',alt:['lgw','gatwick','london']},
  {code:'STN',name:'Londres-Stansted',city:'Londres',country:'UK',flag:'🇬🇧',x:49,y:25,type:'budget',alt:['stn','stansted','london']},
  {code:'EDI',name:'Edimburgo-International',city:'Edimburgo',country:'UK',flag:'🇬🇧',x:48,y:22,type:'main',alt:['edi','edinburgh','escocia','scotland']},
  {code:'DUB',name:'Dublin-Internacional',city:'Dublin',country:'Irlanda',flag:'🇮🇪',x:46,y:24,type:'main',alt:['dub','dublin','irlanda','ireland'],lat:53.43,lng:-6.27},
  {code:'ZRH',name:'Zurique-Kloten',city:'Zurique',country:'Suíça',flag:'🇨🇭',x:52,y:28,type:'main',alt:['zrh','zurique','zurich','suica'],lat:47.46,lng:8.55},
  {code:'GVA',name:'Genebra-Cointrin',city:'Genebra',country:'Suíça',flag:'🇨🇭',x:51,y:29,type:'main',alt:['gva','genebra','geneva','suica']},
  {code:'VIE',name:'Viena-Schwechat',city:'Viena',country:'Áustria',flag:'🇦🇹',x:55,y:27,type:'main',alt:['vie','viena','vienna','austria'],lat:48.12,lng:16.57},
  {code:'BRU',name:'Bruxelas-Nacional',city:'Bruxelas',country:'Bélgica',flag:'🇧🇪',x:51,y:25,type:'main',alt:['bru','bruxelas','brussels','belgica'],lat:50.9,lng:4.48},
  {code:'CPH',name:'Copenhague-Kastrup',city:'Copenhague',country:'Dinamarca',flag:'🇩🇰',x:53,y:22,type:'main',alt:['cph','copenhague','copenhagen','dinamarca'],lat:55.62,lng:12.66},
  {code:'OSL',name:'Oslo-Gardermoen',city:'Oslo',country:'Noruega',flag:'🇳🇴',x:53,y:18,type:'main',alt:['osl','oslo','noruega','norway'],lat:60.2,lng:11.08},
  {code:'ARN',name:'Estocolmo-Arlanda',city:'Estocolmo',country:'Suécia',flag:'🇸🇪',x:55,y:20,type:'main',alt:['arn','estocolmo','stockholm','suecia'],lat:59.65,lng:17.92},
  {code:'HEL',name:'Helsinque-Vantaa',city:'Helsinque',country:'Finlândia',flag:'🇫🇮',x:58,y:19,type:'main',alt:['hel','helsinque','helsinki','finlandia'],lat:60.32,lng:24.97},
  {code:'KEF',name:'Reykjavik-Keflavik',city:'Reykjavik',country:'Islândia',flag:'🇮🇸',x:42,y:12,type:'main',alt:['kef','reykjavik','islandia','aurora boreal']},
  {code:'ATH',name:'Atenas-Eleftherios Venizelos',city:'Atenas',country:'Grécia',flag:'🇬🇷',x:56,y:36,type:'main',alt:['ath','atenas','athens','grecia'],lat:37.94,lng:23.95},
  {code:'HER',name:'Heraklion-Nikos Kazantzakis',city:'Heraklion',country:'Grécia',flag:'🇬🇷',x:57,y:37,type:'main',alt:['her','heraklion','creta','crete'],lat:35.34,lng:25.18},
  {code:'JTR',name:'Santorini-Thira',city:'Santorini',country:'Grécia',flag:'🇬🇷',x:57,y:36,type:'sec',alt:['jtr','santorini','thira','ciclades'],lat:36.4,lng:25.48},
  {code:'JMK',name:'Mikonos',city:'Mikonos',country:'Grécia',flag:'🇬🇷',x:57,y:36,type:'sec',alt:['jmk','mykonos','mikonos'],lat:37.44,lng:25.35},
  {code:'PRG',name:'Praga-Václav Havel',city:'Praga',country:'República Tcheca',flag:'🇨🇿',x:54,y:26,type:'main',alt:['prg','praga','prague','tcheca','czech'],lat:50.1,lng:14.26},
  {code:'BUD',name:'Budapeste-Liszt Ferenc',city:'Budapeste',country:'Hungria',flag:'🇭🇺',x:56,y:27,type:'main',alt:['bud','budapeste','budapest','hungria'],lat:47.44,lng:19.26},
  {code:'KRK',name:'Cracóvia-João Paulo II',city:'Cracóvia',country:'Polônia',flag:'🇵🇱',x:56,y:25,type:'main',alt:['krk','cracovia','krakow','polonia']},
  {code:'WAW',name:'Varsóvia-Chopin',city:'Varsóvia',country:'Polônia',flag:'🇵🇱',x:57,y:24,type:'main',alt:['waw','varsovia','warsaw','polonia'],lat:52.17,lng:20.97},
  {code:'IST',name:'Istambul-Istanbul',city:'Istambul',country:'Turquia',flag:'🇹🇷',x:59,y:32,type:'main',alt:['ist','istambul','istanbul','turquia','turkey'],lat:41.26,lng:28.74},
  {code:'SAW',name:'Istambul-Sabiha Gökçen',city:'Istambul',country:'Turquia',flag:'🇹🇷',x:59,y:32,type:'budget',alt:['saw','sabiha','istanbul'],lat:40.9,lng:29.31},
  {code:'AYT',name:'Antalya-Internacional',city:'Antalya',country:'Turquia',flag:'🇹🇷',x:58,y:34,type:'main',alt:['ayt','antalya','riviera turca','turquia']},
  {code:'DUS',name:'Düsseldorf-Internacional',city:'Düsseldorf',country:'Alemanha',flag:'🇩🇪',x:52,y:25,type:'main',alt:['dus','dusseldorf','renania']},
  {code:'HAM',name:'Hamburgo-Internacional',city:'Hamburgo',country:'Alemanha',flag:'🇩🇪',x:53,y:23,type:'main',alt:['ham','hamburgo','hamburg']},
  {code:'LJU',name:'Ljubljana-Jože Pučnik',city:'Ljubljana',country:'Eslovênia',flag:'🇸🇮',x:54,y:29,type:'main',alt:['lju','liubliana','eslovenia','slovenia']},
  {code:'DBV',name:'Dubrovnik-Internacional',city:'Dubrovnik',country:'Croácia',flag:'🇭🇷',x:55,y:31,type:'main',alt:['dbv','dubrovnik','croacia','adriatico']},
  {code:'SPU',name:'Split-Internacional',city:'Split',country:'Croácia',flag:'🇭🇷',x:54,y:31,type:'main',alt:['spu','split','croacia','dalmacia']},
  {code:'RIX',name:'Riga-Internacional',city:'Riga',country:'Letônia',flag:'🇱🇻',x:58,y:21,type:'main',alt:['rix','riga','letonia','balticos']},
  {code:'TLL',name:'Tallinn-Lennart Meri',city:'Tallinn',country:'Estônia',flag:'🇪🇪',x:59,y:20,type:'main',alt:['tll','tallinn','estonia','balticos']},
  // ── Ásia ─────────────────────────────────────────
  {code:'BKK',name:'Bangkok-Suvarnabhumi',city:'Bangkok',country:'Tailândia',flag:'🇹🇭',x:76,y:50,type:'main',alt:['bkk','bangkok','tailandia','thailand'],lat:13.68,lng:100.75},
  {code:'DMK',name:'Bangkok-Don Mueang',city:'Bangkok',country:'Tailândia',flag:'🇹🇭',x:76,y:50,type:'budget',alt:['dmk','don mueang']},
  {code:'HKT',name:'Phuket-Internacional',city:'Phuket',country:'Tailândia',flag:'🇹🇭',x:76,y:53,type:'main',alt:['hkt','phuket','tailandia']},
  {code:'USM',name:'Koh Samui',city:'Koh Samui',country:'Tailândia',flag:'🇹🇭',x:77,y:52,type:'sec',alt:['usm','ko samui','samui']},
  {code:'KUL',name:'Kuala Lumpur-KLIA',city:'Kuala Lumpur',country:'Malásia',flag:'🇲🇾',x:77,y:56,type:'main',alt:['kul','kl','kuala lumpur','malasia'],lat:2.74,lng:101.71},
  {code:'SGN',name:'Ho Chi Minh-Tân Sơn Nhất',city:'Ho Chi Minh',country:'Vietnã',flag:'🇻🇳',x:78,y:52,type:'main',alt:['sgn','saigon','ho chi minh','vietnam','vietna'],lat:10.82,lng:106.66},
  {code:'HAN',name:'Hanói-Nội Bài',city:'Hanói',country:'Vietnã',flag:'🇻🇳',x:78,y:47,type:'main',alt:['han','hanoi','vietnam'],lat:21.22,lng:105.81},
  {code:'DAD',name:'Da Nang-Internacional',city:'Da Nang',country:'Vietnã',flag:'🇻🇳',x:78,y:49,type:'main',alt:['dad','da nang','hoi an','vietnam'],lat:16.04,lng:108.2},
  {code:'SIN',name:'Singapura-Changi',city:'Singapura',country:'Singapura',flag:'🇸🇬',x:78,y:57,type:'main',alt:['sin','singapore','singapura'],lat:1.36,lng:103.99},
  {code:'NRT',name:'Tóquio-Narita',city:'Tóquio',country:'Japão',flag:'🇯🇵',x:86,y:34,type:'main',alt:['nrt','toquio','tokyo','japao','japan'],lat:35.77,lng:140.39},
  {code:'HND',name:'Tóquio-Haneda',city:'Tóquio',country:'Japão',flag:'🇯🇵',x:86,y:34,type:'budget',alt:['hnd','haneda','tokyo'],lat:35.55,lng:139.78},
  {code:'KIX',name:'Osaka-Kansai',city:'Osaka',country:'Japão',flag:'🇯🇵',x:85,y:35,type:'main',alt:['kix','osaka','kansai','kyoto','nara'],lat:34.43,lng:135.24},
  {code:'CTS',name:'Sapporo-Chitose',city:'Sapporo',country:'Japão',flag:'🇯🇵',x:87,y:30,type:'main',alt:['cts','sapporo','hokkaido','neve'],lat:42.77,lng:141.69},
  {code:'ICN',name:'Seul-Incheon',city:'Seul',country:'Coreia do Sul',flag:'🇰🇷',x:84,y:33,type:'main',alt:['icn','seul','seoul','coreia','korea'],lat:37.47,lng:126.45},
  {code:'PEK',name:'Pequim-Capital',city:'Pequim',country:'China',flag:'🇨🇳',x:82,y:34,type:'main',alt:['pek','pequim','beijing','china'],lat:40.08,lng:116.59},
  {code:'PVG',name:'Xangai-Pudong',city:'Xangai',country:'China',flag:'🇨🇳',x:84,y:37,type:'main',alt:['pvg','xangai','shanghai','china'],lat:31.14,lng:121.81},
  {code:'HKG',name:'Hong Kong-Chek Lap Kok',city:'Hong Kong',country:'China',flag:'🇭🇰',x:81,y:40,type:'main',alt:['hkg','hong kong','hongkong'],lat:22.31,lng:113.92},
  {code:'DEL',name:'Nova Delhi-Indira Gandhi',city:'Nova Delhi',country:'Índia',flag:'🇮🇳',x:70,y:40,type:'main',alt:['del','delhi','india','india'],lat:28.56,lng:77.1},
  {code:'BOM',name:'Mumbai-Chhatrapati Shivaji',city:'Mumbai',country:'Índia',flag:'🇮🇳',x:70,y:46,type:'main',alt:['bom','mumbai','bombaim','india'],lat:19.09,lng:72.87},
  {code:'MAA',name:'Chennai-Internacional',city:'Chennai',country:'Índia',flag:'🇮🇳',x:72,y:49,type:'main',alt:['maa','chennai','madras','india sul'],lat:12.99,lng:80.17},
  {code:'BLR',name:'Bangalore-Kempegowda',city:'Bangalore',country:'Índia',flag:'🇮🇳',x:71,y:49,type:'main',alt:['blr','bangalore','bengaluru','india'],lat:13.2,lng:77.71},
  {code:'GOI',name:'Goa-Dabolim',city:'Goa',country:'Índia',flag:'🇮🇳',x:70,y:47,type:'main',alt:['goi','goa','india']},
  {code:'KTM',name:'Katmandu-Tribhuvan',city:'Katmandu',country:'Nepal',flag:'🇳🇵',x:73,y:40,type:'main',alt:['ktm','katmandu','nepal','himalaia','everest'],lat:27.7,lng:85.36},
  {code:'CMB',name:'Colombo-Bandaranaike',city:'Colombo',country:'Sri Lanka',flag:'🇱🇰',x:72,y:52,type:'main',alt:['cmb','colombo','sri lanka','ceilao'],lat:7.18,lng:79.88},
  {code:'DPS',name:'Bali-Ngurah Rai',city:'Bali',country:'Indonésia',flag:'🇮🇩',x:80,y:60,type:'main',alt:['dps','bali','indonesia','ubud','seminyak'],lat:-8.75,lng:115.17},
  {code:'CGK',name:'Jacarta-Soekarno-Hatta',city:'Jacarta',country:'Indonésia',flag:'🇮🇩',x:78,y:59,type:'main',alt:['cgk','jacarta','jakarta','indonesia'],lat:-6.13,lng:106.66},
  {code:'RGN',name:'Yangon-Internacional',city:'Yangon',country:'Mianmar',flag:'🇲🇲',x:76,y:47,type:'main',alt:['rgn','yangon','rangum','myanmar','birmania'],lat:16.91,lng:96.13},
  {code:'REP',name:'Siem Reap-Internacional',city:'Siem Reap',country:'Camboja',flag:'🇰🇭',x:77,y:50,type:'main',alt:['rep','siem reap','angkor','cambodja','camboja'],lat:13.41,lng:103.81},
  {code:'DAC',name:'Dhaka-Hazrat Shahjalal',city:'Dhaka',country:'Bangladesh',flag:'🇧🇩',x:74,y:44,type:'main',alt:['dac','dhaka','bangladesh'],lat:23.84,lng:90.4},
  {code:'TAS',name:'Tashkent-Internacional',city:'Tashkent',country:'Uzbequistão',flag:'🇺🇿',x:67,y:33,type:'main',alt:['tas','tashkent','uzbequistao','rota da seda']},
  // ── Oriente Médio ────────────────────────────────
  {code:'DXB',name:'Dubai-Internacional',city:'Dubai',country:'Emirados',flag:'🇦🇪',x:64,y:40,type:'main',alt:['dxb','dubai','emirados','eau','uae'],lat:25.25,lng:55.36},
  {code:'AUH',name:'Abu Dhabi-Internacional',city:'Abu Dhabi',country:'Emirados',flag:'🇦🇪',x:64,y:40,type:'main',alt:['auh','abu dhabi','emirados'],lat:24.43,lng:54.65},
  {code:'DOH',name:'Doha-Hamad',city:'Doha',country:'Qatar',flag:'🇶🇦',x:63,y:40,type:'main',alt:['doh','doha','qatar','catar'],lat:25.27,lng:51.61},
  {code:'RUH',name:'Riad-King Khalid',city:'Riad',country:'Arábia Saudita',flag:'🇸🇦',x:62,y:40,type:'main',alt:['ruh','riad','riyadh','arabia saudita'],lat:24.96,lng:46.7},
  {code:'TLV',name:'Tel Aviv-Ben Gurion',city:'Tel Aviv',country:'Israel',flag:'🇮🇱',x:58,y:36,type:'main',alt:['tlv','tel aviv','israel','jerusalem'],lat:32.0,lng:34.88},
  {code:'AMM',name:'Amã-Queen Alia',city:'Amã',country:'Jordânia',flag:'🇯🇴',x:59,y:37,type:'main',alt:['amm','ama','petra','jordania']},
  // ── África ───────────────────────────────────────
  {code:'CMN',name:'Casablanca-Mohammed V',city:'Casablanca',country:'Marrocos',flag:'🇲🇦',x:47,y:37,type:'main',alt:['cmn','casablanca','marrocos','morocco'],lat:33.37,lng:-7.59},
  {code:'RAK',name:'Marrakech-Menara',city:'Marrakech',country:'Marrocos',flag:'🇲🇦',x:47,y:38,type:'main',alt:['rak','marrakech','marrakesh','marrocos']},
  {code:'FEZ',name:'Fez-Saïss',city:'Fez',country:'Marrocos',flag:'🇲🇦',x:47,y:36,type:'main',alt:['fez','fes','marrocos']},
  {code:'CAI',name:'Cairo-Internacional',city:'Cairo',country:'Egito',flag:'🇪🇬',x:57,y:38,type:'main',alt:['cai','cairo','egito','egypt','piramides'],lat:30.12,lng:31.41},
  {code:'HRG',name:'Hurghada-Internacional',city:'Hurghada',country:'Egito',flag:'🇪🇬',x:58,y:39,type:'main',alt:['hrg','hurghada','mar vermelho','egito']},
  {code:'NBO',name:'Nairóbi-Jomo Kenyatta',city:'Nairóbi',country:'Quênia',flag:'🇰🇪',x:59,y:58,type:'main',alt:['nbo','nairobi','quenia','safari','africa oriental'],lat:-1.32,lng:36.93},
  {code:'JRO',name:'Kilimanjaro-Internacional',city:'Kilimanjaro',country:'Tanzânia',flag:'🇹🇿',x:59,y:60,type:'main',alt:['jro','kilimanjaro','tanzania','serengeti']},
  {code:'ZNZ',name:'Zanzibar-Abeid Amani Karume',city:'Zanzibar',country:'Tanzânia',flag:'🇹🇿',x:59,y:61,type:'main',alt:['znz','zanzibar','tanzania']},
  {code:'CPT',name:'Cidade do Cabo-International',city:'Cidade do Cabo',country:'África do Sul',flag:'🇿🇦',x:55,y:78,type:'main',alt:['cpt','cidade do cabo','cape town','africa do sul'],lat:-33.96,lng:18.6},
  {code:'JNB',name:'Joanesburgo-OR Tambo',city:'Joanesburgo',country:'África do Sul',flag:'🇿🇦',x:57,y:75,type:'main',alt:['jnb','joanesburgo','johannesburg','africa do sul'],lat:-26.14,lng:28.23},
  {code:'ACC',name:'Accra-Kotoka',city:'Accra',country:'Gana',flag:'🇬🇭',x:49,y:56,type:'main',alt:['acc','accra','gana','ghana'],lat:5.6,lng:-0.17},
  {code:'LOS',name:'Lagos-Murtala Muhammed',city:'Lagos',country:'Nigéria',flag:'🇳🇬',x:50,y:56,type:'main',alt:['los','lagos','nigeria'],lat:6.58,lng:3.32},
  {code:'TNR',name:'Antananarivo-Ivato',city:'Antananarivo',country:'Madagáscar',flag:'🇲🇬',x:62,y:69,type:'main',alt:['tnr','antananarivo','madagascar']},
  // ── América do Norte ─────────────────────────────
  {code:'JFK',name:'Nova York-John F. Kennedy',city:'Nova York',country:'EUA',flag:'🇺🇸',x:23,y:34,type:'main',alt:['jfk','nova york','new york','nyc','ny','eua'],lat:40.64,lng:-73.78},
  {code:'LGA',name:'Nova York-LaGuardia',city:'Nova York',country:'EUA',flag:'🇺🇸',x:23,y:34,type:'main',alt:['lga','laguardia','nova york','nyc']},
  {code:'EWR',name:'Nova York-Newark',city:'Nova York',country:'EUA',flag:'🇺🇸',x:23,y:34,type:'budget',alt:['ewr','newark','nova york','nj']},
  {code:'LAX',name:'Los Angeles-Internacional',city:'Los Angeles',country:'EUA',flag:'🇺🇸',x:13,y:37,type:'main',alt:['lax','los angeles','la','california','eua'],lat:33.94,lng:-118.41},
  {code:'SFO',name:'São Francisco-Internacional',city:'São Francisco',country:'EUA',flag:'🇺🇸',x:12,y:35,type:'main',alt:['sfo','san francisco','california','silicon valley'],lat:37.62,lng:-122.39},
  {code:'ORD',name:'Chicago-O\'Hare',city:'Chicago',country:'EUA',flag:'🇺🇸',x:20,y:33,type:'main',alt:['ord','chicago','illinois','eua'],lat:41.97,lng:-87.9},
  {code:'MIA',name:'Miami-Internacional',city:'Miami',country:'EUA',flag:'🇺🇸',x:21,y:42,type:'main',alt:['mia','miami','florida','eua'],lat:25.8,lng:-80.29},
  {code:'MCO',name:'Orlando-Internacional',city:'Orlando',country:'EUA',flag:'🇺🇸',x:21,y:41,type:'main',alt:['mco','orlando','disney','florida'],lat:28.43,lng:-81.31},
  {code:'LAS',name:'Las Vegas-Harry Reid',city:'Las Vegas',country:'EUA',flag:'🇺🇸',x:14,y:37,type:'main',alt:['las','las vegas','nevada','strip'],lat:36.08,lng:-115.15},
  {code:'YYZ',name:'Toronto-Pearson',city:'Toronto',country:'Canadá',flag:'🇨🇦',x:21,y:31,type:'main',alt:['yyz','toronto','canada','ontario'],lat:43.68,lng:-79.63},
  {code:'YVR',name:'Vancouver-Internacional',city:'Vancouver',country:'Canadá',flag:'🇨🇦',x:12,y:30,type:'main',alt:['yvr','vancouver','bc','canada']},
  {code:'YUL',name:'Montreal-Trudeau',city:'Montreal',country:'Canadá',flag:'🇨🇦',x:22,y:31,type:'main',alt:['yul','montreal','quebec','canada']},
  {code:'MEX',name:'Cidade do México-Benito Juárez',city:'Cidade do México',country:'México',flag:'🇲🇽',x:17,y:46,type:'main',alt:['mex','cdmx','mexico city','mexico'],lat:19.44,lng:-99.07},
  {code:'CUN',name:'Cancún-Internacional',city:'Cancún',country:'México',flag:'🇲🇽',x:20,y:46,type:'main',alt:['cun','cancun','riviera maya','mexico'],lat:21.04,lng:-86.87},
  {code:'HAV',name:'Havana-José Martí',city:'Havana',country:'Cuba',flag:'🇨🇺',x:21,y:44,type:'main',alt:['hav','havana','cuba']},
  {code:'PTY',name:'Panamá-Tocumen',city:'Panamá',country:'Panamá',flag:'🇵🇦',x:23,y:52,type:'main',alt:['pty','panama city','panama','canal do panama']},
  {code:'SJO',name:'San José-Juan Santamaría',city:'San José',country:'Costa Rica',flag:'🇨🇷',x:21,y:51,type:'main',alt:['sjo','san jose','costa rica','pura vida']},
  {code:'GUA',name:'Guatemala-La Aurora',city:'Guatemala City',country:'Guatemala',flag:'🇬🇹',x:19,y:48,type:'main',alt:['gua','guatemala','tikal']},
  {code:'SAL',name:'San Salvador-Óscar Romero',city:'San Salvador',country:'El Salvador',flag:'🇸🇻',x:20,y:49,type:'main',alt:['sal','san salvador','el salvador']},
  // ── Oceania ──────────────────────────────────────
  {code:'SYD',name:'Sydney-Kingsford Smith',city:'Sydney',country:'Austrália',flag:'🇦🇺',x:88,y:73,type:'main',alt:['syd','sydney','australia','operahouse'],lat:-33.95,lng:151.18},
  {code:'MEL',name:'Melbourne-Tullamarine',city:'Melbourne',country:'Austrália',flag:'🇦🇺',x:87,y:75,type:'main',alt:['mel','melbourne','australia'],lat:-37.67,lng:144.84},
  {code:'BNE',name:'Brisbane-Internacional',city:'Brisbane',country:'Austrália',flag:'🇦🇺',x:88,y:71,type:'main',alt:['bne','brisbane','queensland','gold coast'],lat:-27.38,lng:153.12},
  {code:'PER',name:'Perth-Internacional',city:'Perth',country:'Austrália',flag:'🇦🇺',x:82,y:73,type:'main',alt:['per','perth','western australia'],lat:-31.94,lng:115.97},
  {code:'AKL',name:'Auckland-Internacional',city:'Auckland',country:'Nova Zelândia',flag:'🇳🇿',x:93,y:77,type:'main',alt:['akl','auckland','nova zelandia','nz'],lat:-37.01,lng:174.79},
  {code:'CHC',name:'Christchurch-Internacional',city:'Christchurch',country:'Nova Zelândia',flag:'🇳🇿',x:93,y:79,type:'main',alt:['chc','christchurch','nz','ilha sul'],lat:-43.49,lng:172.54},
  {code:'PPT',name:'Papeete-Faa\'a',city:'Papeete',country:'Polinésia Francesa',flag:'🇵🇫',x:94,y:63,type:'main',alt:['ppt','papeete','tahiti','bora bora','polinesia'],lat:-17.56,lng:-149.61},
  {code:'APW',name:'Apia-Faleolo',city:'Apia',country:'Samoa',flag:'🇼🇸',x:95,y:65,type:'main',alt:['apw','apia','samoa'],lat:-13.83,lng:-172.0},
  // ── Cidades menores / destinos turísticos ─────────
  {code:'VLC',name:'Valência-Internacional',city:'Valência',country:'Espanha',flag:'🇪🇸',x:49,y:34,type:'main',alt:['vlc','valencia','comunitat valenciana']},
  {code:'SVQ',name:'Sevilha-San Pablo',city:'Sevilha',country:'Espanha',flag:'🇪🇸',x:47,y:35,type:'main',alt:['svq','sevilha','seville','andaluzia','flamenco'],lat:37.42,lng:-5.89},
  {code:'BIO',name:'Bilbao-Internacional',city:'Bilbao',country:'Espanha',flag:'🇪🇸',x:48,y:32,type:'main',alt:['bio','bilbao','pais basco','guggenheim'],lat:43.3,lng:-2.91},
  {code:'TNG',name:'Tânger-Ibn Battuta',city:'Tânger',country:'Marrocos',flag:'🇲🇦',x:47,y:36,type:'main',alt:['tng','tanger','marrocos','estreito gibraltar']},
  {code:'EBL',name:'Erbil-Internacional',city:'Erbil',country:'Iraque',flag:'🇮🇶',x:62,y:36,type:'main',alt:['ebl','erbil','kurdistao','iraque']},
  {code:'MRU',name:'Maurício-Sir Seewoosagur',city:'Maurício',country:'Maurício',flag:'🇲🇺',x:64,y:68,type:'main',alt:['mru','mauricio','mauritius','ilha mauricio'],lat:-20.43,lng:57.68},
  {code:'SEZ',name:'Seychelles-Internacional',city:'Mahé',country:'Seychelles',flag:'🇸🇨',x:63,y:60,type:'main',alt:['sez','seychelles','mahe','aldabra'],lat:-4.67,lng:55.52},
  {code:'MLE',name:'Malé-Velana',city:'Malé',country:'Maldivas',flag:'🇲🇻',x:72,y:55,type:'main',alt:['mle','male','maldivas','maldives','atol'],lat:4.19,lng:73.53},
];
const eAirports = eAPS; // alias para compatibilidade
